databases:
  - name: webhook-subscriber

services:
  - type: web
    name: webhook-subscriber
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-subscriber
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false